import type { BuiltInTemplateCategory, TemplateProfile } from "@/types/ppt";

export const builtInTemplates: TemplateProfile[] = [
  {
    id: "boardroom-brief",
    name: "Boardroom Brief",
    source: "built-in",
    category: "business",
    pageCount: 12,
    aspectRatio: "16:9",
    dominantColors: ["#102820", "#F2F5EA", "#C2A83E", "#4A6B57"],
    fonts: ["Aptos Display", "Aptos"],
    titleHierarchy: ["cover title", "section title", "content heading"],
    detectedLayouts: ["cover", "agenda", "two-column", "metric callout", "closing"],
    hasCover: true,
    hasAgenda: true,
    hasClosing: true,
    thumbnail: "linear-gradient(135deg,#102820 0%,#102820 52%,#f2f5ea 52%,#f2f5ea 100%)",
    warnings: [],
    fallbackStrategy: "Use built-in executive layouts with dark cover and light content slides.",
  },
  {
    id: "defense-grid",
    name: "Defense Grid",
    source: "built-in",
    category: "academic",
    pageCount: 16,
    aspectRatio: "16:9",
    dominantColors: ["#1F2A44", "#F7F8FA", "#2E8BC0", "#D8DEE9"],
    fonts: ["Cambria", "Calibri"],
    titleHierarchy: ["research title", "chapter heading", "evidence label"],
    detectedLayouts: ["cover", "agenda", "method", "comparison", "reference"],
    hasCover: true,
    hasAgenda: true,
    hasClosing: true,
    thumbnail: "linear-gradient(90deg,#1f2a44 0 34%,#f7f8fa 34% 100%)",
    warnings: [],
    fallbackStrategy: "Use academic typography, evidence panels, and method/result layouts.",
  },
  {
    id: "venture-signal",
    name: "Venture Signal",
    source: "built-in",
    category: "startup",
    pageCount: 10,
    aspectRatio: "16:9",
    dominantColors: ["#141414", "#F6F1E8", "#FF5A3D", "#2F80ED"],
    fonts: ["Aptos Display", "Aptos"],
    titleHierarchy: ["pitch title", "traction number", "section label"],
    detectedLayouts: ["cover", "problem", "solution", "market", "financials"],
    hasCover: true,
    hasAgenda: false,
    hasClosing: true,
    thumbnail: "linear-gradient(135deg,#141414 0 62%,#ff5a3d 62% 70%,#f6f1e8 70%)",
    warnings: [],
    fallbackStrategy: "Use sharp pitch-deck layouts with traction callouts and concise evidence blocks.",
  },
  {
    id: "product-lab",
    name: "Product Lab",
    source: "built-in",
    category: "product",
    pageCount: 14,
    aspectRatio: "16:9",
    dominantColors: ["#12343B", "#E8F1F2", "#2CA58D", "#F4A261"],
    fonts: ["Trebuchet MS", "Calibri"],
    titleHierarchy: ["product title", "feature heading", "UX note"],
    detectedLayouts: ["cover", "feature grid", "roadmap", "persona", "demo"],
    hasCover: true,
    hasAgenda: true,
    hasClosing: true,
    thumbnail: "linear-gradient(145deg,#12343b 0 48%,#2ca58d 48% 54%,#e8f1f2 54%)",
    warnings: [],
    fallbackStrategy: "Use product storytelling layouts with feature blocks, roadmap lanes, and demo notes.",
  },
  {
    id: "lesson-flow",
    name: "Lesson Flow",
    source: "built-in",
    category: "education",
    pageCount: 18,
    aspectRatio: "16:9",
    dominantColors: ["#273469", "#FAFAFF", "#F9C80E", "#66A182"],
    fonts: ["Georgia", "Calibri"],
    titleHierarchy: ["lesson title", "module heading", "activity prompt"],
    detectedLayouts: ["cover", "objective", "concept", "exercise", "recap"],
    hasCover: true,
    hasAgenda: true,
    hasClosing: true,
    thumbnail: "linear-gradient(120deg,#273469 0 45%,#fafaff 45% 100%)",
    warnings: [],
    fallbackStrategy: "Use instructional pacing with objectives, exercises, recap, and speaker prompts.",
  },
  {
    id: "data-room",
    name: "Data Room",
    source: "built-in",
    category: "data",
    pageCount: 15,
    aspectRatio: "16:9",
    dominantColors: ["#202124", "#FFFFFF", "#00A6A6", "#EF476F"],
    fonts: ["Consolas", "Calibri"],
    titleHierarchy: ["analysis title", "metric title", "insight label"],
    detectedLayouts: ["cover", "dashboard", "chart", "comparison", "recommendation"],
    hasCover: true,
    hasAgenda: true,
    hasClosing: true,
    thumbnail: "linear-gradient(90deg,#202124 0 30%,#fff 30% 100%)",
    warnings: [],
    fallbackStrategy: "Use dense but readable analysis slides with metric callouts and chart-first layouts.",
  },
];

export function getBuiltInTemplate(id: string): TemplateProfile {
  return builtInTemplates.find((template) => template.id === id) ?? builtInTemplates[0];
}

export function getCategoryLabel(category?: BuiltInTemplateCategory) {
  const labels: Record<BuiltInTemplateCategory, string> = {
    business: "商务汇报",
    academic: "学术答辩",
    startup: "创业融资",
    product: "产品介绍",
    education: "教育培训",
    data: "数据分析",
  };

  return category ? labels[category] : "自定义";
}
